auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: YangQian.site
url: http://YangQian.site
feed: /atom.xml
author_info: <a href="http://YangQian.site/">YangQian</a>
